version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver
  identity:
    build:
      context: .
      dockerfile: Dockerfile.Identity
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "MyDatabaseSecret123"
      ACCEPT_EULA: "Y"